# Generated by Django 3.1 on 2023-02-04 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_blog_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_dec',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='decription',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
