# Generated by Django 3.1 on 2023-01-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_dec', models.CharField(max_length=100)),
                ('event_date', models.CharField(max_length=100)),
                ('event_address', models.CharField(max_length=100)),
            ],
        ),
    ]
