# Generated by Django 4.1.7 on 2023-03-12 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0002_alter_style_name'),
        ('video', '0002_video_video_file_alter_comment_id_alter_video_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style', to='style.style'),
        ),
    ]
