# Generated by Django 4.1.7 on 2023-03-12 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0002_alter_style_name'),
        ('video', '0003_alter_video_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_style', to='style.style'),
        ),
    ]
